### ISSUE TITLE
Remove scratch parameter from nextflow.config

### ISSUE THREAD

**Issue by drejom** [phelelani/nf-rnaSeqMetagen#1]
Setting `scratch` with an absolute path in the pipeline `nextflow.config` breaks the tutorial example: 

https://github.com/phelelani/nf-rnaSeqMetagen/blob/3375836ec7ac76911e6bdb1263b43c3b9b7e0c0c/nextflow.config#L151

Should move this parameter to your personal `~/.nexflow/config`

**Comment by phelelani** [comment]
@drejom - Thank you for making me aware of this issue. We had to add the scratch directory in the `nextflow.config` to overcome some issues we were having on our cluster at the time of testing. I have removed this from the code.
